services:
  devopsjava:
    build:
      context: ./
      dockerfile: Dockerfile

    image: devopsjava:v3.0.0
    container_name: devops_container
    ports:
      - "80:8080"
    restart: unless-stopped

